<?= "<?php",PHP_EOL ?>

namespace <?= $this->entities_namespace ?>;

use Tabusoft\ORM\Entity\EntityAbstract;
use <?= $this->entities_descriptor_namespace ?>\<?= $this->entity_descriptor_name ?>;

/**
*
* @database <?= $this->database, PHP_EOL ?>
* @table <?= $this->table_name, PHP_EOL ?>
*
**/
class <?= $this->entity_name; ?> extends EntityAbstract
{
    use <?= $this->entity_descriptor_name ?>;

    /** implements here your class methods */

}
